program = cmnd | program"\n"cmnd;
cmnd    = "print "expr";";
expr    = term | expr "+" term | expr "-" term;
term    = factor | term "*" factor | term "/" factor;
factor  = integer | "("expr")";
integer = digit | integer digit;
digit   = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9";